[package]
name = "rusty-raft"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
rand = "0.8"
tracing = "0.1"

[dev-dependencies]
turmoil = "0.6"
tracing-subscriber = "0.3"
